<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'task_list' => [[], ['_controller' => 'App\\Controller\\TaskController::index'], [], [['text', '/tasks']], [], [], []],
    'task_add' => [[], ['_controller' => 'App\\Controller\\TaskController::add'], [], [['text', '/tasks/add']], [], [], []],
    'task_delete' => [['id'], ['_controller' => 'App\\Controller\\TaskController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/tasks/delete']], [], [], []],
    'App\Controller\TaskController::index' => [[], ['_controller' => 'App\\Controller\\TaskController::index'], [], [['text', '/tasks']], [], [], []],
    'App\Controller\TaskController::add' => [[], ['_controller' => 'App\\Controller\\TaskController::add'], [], [['text', '/tasks/add']], [], [], []],
    'App\Controller\TaskController::delete' => [['id'], ['_controller' => 'App\\Controller\\TaskController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/tasks/delete']], [], [], []],
];
