<?php

namespace ContainerOXxOKz8;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VwZj2VZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VwZj2VZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VwZj2VZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'task' => ['privates', '.errored..service_locator.VwZj2VZ.App\\Entity\\Task', NULL, 'Cannot autowire service ".service_locator.VwZj2VZ": it needs an instance of "App\\Entity\\Task" but this type has been excluded in "config/services.yaml".'],
        ], [
            'manager' => '?',
            'task' => 'App\\Entity\\Task',
        ]);
    }
}
